function test_suite = test_layout_derivatives %#ok<*STOUT>
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_layout_schemaless()

  pth_bids_example = get_test_data_dir();

  use_schema = false();

  BIDS = bids.layout(fullfile(pth_bids_example, ...
                              'ds000001-fmriprep'), use_schema);

  modalities = {'anat', 'figures', 'func'};
  assertEqual(bids.query(BIDS, 'modalities'), modalities);

  % Those fail for now
  %   data = bids.query(BIDS, 'data', ...
  %                     'sub', '10', ...
  %                     'modality', 'func', ...
  %                     'suffix', 'bold', ...
  %                     'run', '1', ...
  %                     'res', '2');
  %   data = bids.query(BIDS, 'data', ...
  %                     'sub', '10', ...
  %                     'modality', 'func', ...
  %                     'suffix', 'bold', ...
  %                     'run', '1', ...
  %                     'space', 'MNI152NLin6Asym');

end

function test_layout_nested_derivatives()

  pth_bids_example = get_test_data_dir();

  use_schema = false();

  BIDS = bids.layout(fullfile(pth_bids_example, ...
                              'ds000117', ...
                              'derivatives', ...
                              'meg_derivatives'), use_schema);

  modalities = {'meg'};
  assertEqual(bids.query(BIDS, 'modalities'), modalities);

  data = bids.query(BIDS, 'data', ...
                    'sub', '01', ...
                    'run', '01', ...
                    'proc', 'sss', ...
                    'suffix', 'meg');
  basename = bids.internal.file_utils(data, 'basename');
  assertEqual(basename, {'sub-01_ses-meg_task-facerecognition_run-01_proc-sss_meg'});

end
