function test_suite = test_download_ds %#ok<*STOUT>

  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;

end

function test_download_ds_moae()

  rmdir(fullfile(bids.internal.root_dir(), 'tmp'), 's');

  output_dir = bids.util.download_ds('source', 'spm', ...
                                     'demo', 'moae', ...
                                     'out_path', fullfile(bids.internal.root_dir(), 'tmp'), ...
                                     'force', false, ...
                                     'verbose', true, ...
                                     'delete_previous', false);

  output_dir = bids.util.download_ds('source', 'spm', ...
                                     'demo', 'moae', ...
                                     'out_path', fullfile(bids.internal.root_dir(), 'tmp'), ...
                                     'force', true, ...
                                     'verbose', true, ...
                                     'delete_previous', false);

  output_dir = bids.util.download_ds('source', 'spm', ...
                                     'demo', 'moae', ...
                                     'out_path', fullfile(bids.internal.root_dir(), 'tmp'), ...
                                     'force', true, ...
                                     'verbose', true, ...
                                     'delete_previous', true);

  rmdir(output_dir, 's');

end

function test_download_ds_facerep()

  output_dir = bids.util.download_ds('source', 'spm', ...
                                     'demo', 'facerep', ...
                                     'out_path', fullfile(bids.internal.root_dir(), 'tmp'), ...
                                     'force', true, ...
                                     'verbose', true, ...
                                     'delete_previous', true);

  rmdir(output_dir, 's');

end
