function test_suite = test_keep_file %#ok<*STOUT>
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;

end

function test_keep_file_exclude_based_on_modality()

  file_struct = struct('modality', 'func', ...
                       'suffix', 'bold', ...
                       'ext', '.nii.gz', ...
                       'entities', struct('task', 'balloon', ...
                                          'ses', '01', ...
                                          'sub', '02', ...
                                          'acq', 'fullbrain', ...
                                          'rec', ''), ...
                       'prefix', 'swau');

  options = {'modality', {'anat'}};
  assertEqual(bids.internal.keep_file_for_query(file_struct, options), false);

end

function test_keep_file_basic()

  cfg = set_test_cfg();

  file_struct = struct('suffix', 'bold', ...
                       'ext', '.nii.gz', ...
                       'entities', struct('task', 'balloon', ...
                                          'ses', '01', ...
                                          'sub', '02', ...
                                          'acq', 'fullbrain'), ...
                       'prefix', 'swau');

  options_and_expected_result = {{'ses', {'01'}},                                     true; ...
                                 {'ses', {'02'}},                                     false; ...
                                 {'ses', {'01'}; 'acq', {'frontal'}},                 false; ...
                                 {'ses', {'01', '02'}},                               true; ...
                                 {'suffix', {'T1w'}},                                 false; ...
                                 {'suffix', {'bold'}},                                true; ...
                                 {'suffix', {'bold'}; 'extension', {'.nii'}},         false; ...
                                 {'suffix', {'bold'}; 'prefix', {''}}                 false; ...
                                 {'suffix', {'T1w', 'bold'}},                         true; ...
                                 {'sub', {'02'}; 'ses', {'01'}},                      true; ...
                                 {'sub', {'02'}; 'ses', {'02'}}                       false; ...
                                 {'sub', {'02'}; 'ses', {'01'}; 'suffix', {'T1w'}},   false; ...
                                 {'sub', {'02'}; 'task', {'balloon'}},                true };

  for iTest = 1:size(options_and_expected_result, 1)
    options = options_and_expected_result{iTest, 1};
    expected_result = options_and_expected_result{iTest, 2};
    assertEqual(bids.internal.keep_file_for_query(file_struct, options), expected_result);
  end

  file_struct = struct('suffix', 'T1w', ...
                       'entities', struct('ses', '01', ...
                                          'sub', '02'));
  options = {'sub', {'02'}
             'task', {'balloon'}};

  assertEqual(bids.internal.keep_file_for_query(file_struct, options), false);

end

function test_keep_file_exclude_entity()

  file_struct = struct('suffix', 'bold', ...
                       'ext', '.nii.gz', ...
                       'entities', struct('task', 'balloon', ...
                                          'ses', '01', ...
                                          'sub', '02', ...
                                          'acq', 'fullbrain', ...
                                          'rec', ''), ...
                       'prefix', 'swau');

  options = {'ses', {'01'}
             'rec', {''}};
  assertEqual(bids.internal.keep_file_for_query(file_struct, options), true);

end

function test_keep_file_events_in_root()

  file_struct = struct('prefix', '', ...
                       'suffix', 'events', ...
                       'ext', '.tsv', ...
                       'entities', struct('task', 'nback'));

  options = {'sub', {'01'}};
  assertEqual(bids.internal.keep_file_for_query(file_struct, options), false);

end
