function test_suite = test_append_to_layout %#ok<*STOUT>
  try % assignment of 'localfunctions' is necessary in Matlab >= 2016
    test_functions = localfunctions(); %#ok<*NASGU>
  catch % no problem; early Matlab versions can use initTestSuite fine
  end
  initTestSuite;
end

function test_append_to_layout_basic()

  schema = bids.schema.load_schema();

  subject = struct('anat', struct([]));

  modality = 'anat';

  file = '../sub-16/anat/sub-16_ses-mri_run-1_acq-hd_T1w.nii.gz';
  entities = {'sub', 'ses', 'run', 'acq', 'ce', 'rec', 'part'};
  subject = bids.internal.append_to_layout(file, subject, modality, schema);

  expected.anat = struct( ...
                         'filename', 'sub-16_ses-mri_run-1_acq-hd_T1w.nii.gz', ...
                         'suffix', 'T1w', ...
                         'ext', '.nii.gz', ...
                         'sub', '16', ...
                         'ses', 'mri', ...
                         'run', '1', ...
                         'acq', 'hd', ...
                         'ce', '', ...
                         'rec', '', ...
                         'part', '');

  assertEqual(subject.anat, expected.anat);

end

function test_append_to_structure_basic_test()

  schema = bids.schema.load_schema();

  subject = struct('anat', struct([]));
  modality = 'anat';

  file = '../sub-16/anat/sub-16_ses-mri_run-1_acq-hd_T1w.nii.gz';
  entities = {'sub', 'ses', 'run', 'acq', 'ce', 'rec', 'part'};
  subject = bids.internal.append_to_layout(file, subject, modality, schema);

  file = '../sub-16/anat/sub-16_ses-mri_run-1_T1map.nii.gz';
  entities = {'sub', 'ses', 'run', 'acq', 'ce', 'rec'};
  subject = bids.internal.append_to_layout(file, subject, modality, schema);

  expected(1).anat = struct( ...
                            'filename', 'sub-16_ses-mri_run-1_acq-hd_T1w.nii.gz', ...
                            'suffix', 'T1w', ...
                            'ext', '.nii.gz', ...
                            'sub', '16', ...
                            'ses', 'mri', ...
                            'run', '1', ...
                            'acq', 'hd', ...
                            'ce', '', ...
                            'rec', '', ...
                            'part', '');

  expected(2).anat = struct( ...
                            'filename', 'sub-16_ses-mri_run-1_T1map.nii.gz', ...
                            'suffix', 'T1map', ...
                            'ext', '.nii.gz', ...
                            'sub', '16', ...
                            'ses', 'mri', ...
                            'run', '1', ...
                            'acq', '', ...
                            'ce', '', ...
                            'rec', '', ...
                            'part', '');     %#ok<*STRNU>

end
