---
name: Bug report

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to report a bug

title: '[BUG]'

labels: ['bug :bug:']

body:

- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

      To maximize chances for a quick fix make sure you know
      [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Operating system
    description: What operating system are you using?
    options:
    - label: Linux
    - label: Mac
    - label: Windows

- type: textarea
  attributes:
    label: Operating system version
    render: Markdown
    value: |
      - Linux Ubuntu 18.04 "bionic beaver"
      - Mac OS Version 12 "monterey"
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Platform
    description: Which platform and version are you running?
    options:
    - label: MATLAB
    - label: Octave

- type: textarea
  attributes:
    label: Platform version
    render: Markdown
    placeholder: |
      - MATLAB 2017a
      - Octave 4.2.2

- type: dropdown
  attributes:
    label: bids-matlab version
    description: |
      In the MATLAB / Octave command line, try one of the following:

       - `bids.bids_matlab_version`

      Or check the content of CITATION.cff.
    options:
    - v0.1.0dev
    - v0.1.0
  validations:
    required: true

- type: textarea
  attributes:
    label: branch / commit number
    description: |
      In a terminal:

       - `git rev-parse --abbrev-ref HEAD`
       - `git rev-parse --short HEAD`

      In the MATLAB command line

       - `[branch, commit] = getRepoInfo()`

    render: Markdown
    value: |
      - main 29b689dd
      - dev 1bda0162

- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe what outcome you expected.
    placeholder: Describe what outcome you expected.
  validations:
    required: false

- type: textarea
  attributes:
    label: Current Behavior
    description: Describe what you got instead.
    placeholder: Describe what you got instead
  validations:
    required: true

- type: textarea
  attributes:
    label: Error message
    description: If possible paste below the error message you encountered.
    render: Markdown
    placeholder: |
      ```matlab
      % this is the error I got

      ```
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
